### ISSUE TITLE
fetchObjects, fetchRows, etc.

### ISSUE THREAD

**Issue by leeoniya** [rkrx/php-mysql-query-builder#2]
hey @rkrx,

i'm trying out this query builder and it feels very well done so far :)

i have a couple comments. i often prefer to work with objects (or `ArrayObject`s) rather than arrays, so i set `PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ`, but `fetchRow` and `fetchRows` has a hard-coded `FETCH_ASSOC`.

what do you think about changing the generic `fetchRow` and `fetchRows` to respect the default fetch mode of the injected `$pdo` and adding `fetchAssoc` and `fetchAssocs` (plural?) that are explicit like `fetchObject` and `fetchObjects`?

thanks!

**Comment by leeoniya** [comment]
also...

`fetchObject($className, ...)` signature would be a bit better as
`fetchObject($className = 'stdClass', ...)`

same for `fetchObjects`

**Comment by rkrx** [comment]
Hey @leeoniya 

thank you for your input!

> i have a couple comments. i often prefer to work with objects (or ArrayObjects) rather than arrays, so i set `PDO::ATTR_DEFAULT_FETCH_MODE` => `PDO::FETCH_OBJ`, but fetchRow and fetchRows has a hard-coded `FETCH_ASSOC`.

I had a discussion with a coworker some time ago about the exact same thing regarding using `PDO::FETCH_OBJ` instead of an hard-coded `PDO::FETCH_ASSOC`. That's why we added `fetchObject` later on. We normally don't use anonymous objects anymore, since we would have no inspection-aid from IDEs like ours.

> what do you think about changing the generic `fetchRow` and `fetchRows` to respect the default fetch mode of the injected `$pdo` and adding `fetchAssoc` and `fetchAssocs` (plural?) that are explicit like `fetchObject` and `fetchObjects`?

The simple reason for the hard-coding is, that I need to be explicit about `fetchRow*`, since these methods are used in inter-project components. They are already used in large internal projects of my company. Having one project, that defines another outcome for `fetchRow` and `fetchRows` would break a lot of things. Renaming `fetchRow*` to `fetchAssoc*` would cause a lot of trouble here and I don't see too much benefit from this. Having a global `PDO::ATTR_DEFAULT_FETCH_MODE` that is able to change the result-type of a method, would be a huge side-effect to begin with.

I see two possible solutions here:

- When using `fetchRow`, you can cast the result to `(object)`.
- As you mentioned, I should change the signature of `fetchObject*` to give `$className` the default-value of `'stdClass'`. Already done with [886dc05](https://github.com/rkrx/php-mysql-query-builder/commit/886dc054e57c0f393b1d47668e997e346f53aaf5). _Wouldn't this be the solution to your issue?_
- You could extend from `MySQL` and override the `select`-method to return a `RunnableSelect` with your implementation of `fetchRow*` or additional methods to match your case. I could imagine to add some sort of factory as a parameter for `__construct` to easily enable substitutes for the builder-classes.

**Comment by leeoniya** [comment]
you're right. having methods return different things based on some deep dependency option would be fairly nasty and surprising...though it *is* how pdo's native fetch/fetchAll work without args. i'll likely do as you suggest and extend the existing classes if needed.

thanks for your help!
